[package]
name = "fs0x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.24"
thiserror = "1.0.57"
url = "2.5.0"
